name: Build WAR file

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn clean package #install sonar:sonar


    #- name: Upload artifact
      #uses: actions/upload-artifact@v3
      #with:
        #name: jacoco
        #path: target/site/jacoco/jacoco.xml

  deploy:
    depends: build
    runs-on: ubuntu-latest   # Adjust the runner as needed

    steps:
      - name: Install SCP
        run: apt-get install -y scp    # Install SCP on the runner

      - name: Copy artifact using SCP
        run:  scp -P 25122 target/SayBigNumber.war root:Entorns23!@ssh.cfgs.esliceu.net:/var/lib/tomcat9/webapps