name: Build WAR file

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'



    - name: Get actions dir path
      uses: michmich112/get-actions-dir-path@v0.0.2

    - name: Build with Maven
      run: mvn clean install sonar:sonar

      
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: jacoco
        path: target/site/jacoco/jacoco.xml
