name: Build WAR file

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Build
      run: mvn clean package #install sonar:sonar

    - name: Deploy
      uses: appleboy/scp-action@master
      with:
        host: "ssh.cfgs.esliceu.net"
        port: 25122
        username: root
        password: Entorns23!
        source: "target/SayBigNumber.war"
        target: "/var/lib/tomcat9/webapps/"
        strip_components: 1
        
    - name: Test
      uses: matt-ball/newman-action@v1.0.4
      with:
        collection: "tests/Say Big Numbers.postman_collection.json"
        environment: "tests/env/EsLiceu.postman_environment.json"
